apiVersion: apps/v1
kind: Deployment
metadata:
  name: project4
  labels:
    app: project4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project4
  template:
    metadata:
      labels:
        app: project4
    spec:
      containers:
      - name: project4
        image: cuongmh/project4:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 80
      imagePullSecrets:
          - name: cuongmh